##### Base FAST API Image #####
FROM tiangolo/uvicorn-gunicorn:python3.9-slim


# Install dependencies
RUN pip install --upgrade pip
RUN pip install poetry
RUN pip install fastapi

# copy the app folder into the container
COPY ./app /app

# Copy poetry files
COPY ./pyproject.toml /app/
RUN poetry install --no-interaction --no-ansi




# set environment variables 
ENV GUNICORN_CMD_ARGS="--preload"
ENV PORT=8000
ENV BEARER_TOKEN $BEARER_TOKEN
ENV APP_ID $APP_ID
ENV APP_SECRET $APP_SECRET

# Embeddings 
ENV COHERE_API_KEY $COHERE_API_KEY
ENV OPEN_API_KEY $OPEN_API_KEY
ENV HUGGING_FACE_PRIVATE_KEY $HUGGING_FACE_PRIVATE_KEY

ENV DATASTORE $DATASTORE
# Pinecone - VectorDB
ENV PINECONE_API_KEY $PINECONE_API_KEY
ENV PINECONE_ENVIRONMENT $PINECONE_ENVIRONMENT
ENV PINECONE_INDEX $PINECONE_INDEX

# Weaviate - VectorDB
ENV WEAVIATE_HOST $WEAVIATE_HOST
ENV WEAVIATE_PORT $WEAVIATE_PORT
ENV WEAVIATE_INDEX $WEAVIATE_INDEX
ENV WEAVIATE_USERNAME $WEAVIATE_USERNAME
ENV WEAVIATE_PASSWORD $WEAVIATE_PASSWORD
ENV WEAVIATE_SCOPES $WEAVIATE_SCOPES 
ENV WEAVIATE_BATCH_SIZE $WEAVIATE_BATCH_SIZE
ENV WEAVIATE_BATCH_DYNAMIC $WEAVIATE_BATCH_DYNAMIC
ENV WEAVIATE_BATCH_TIMEOUT_RETRIES $WEAVIATE_BATCH_TIMEOUT_RETRIES 
ENV WEAVIATE_BATCH_NUM_WORKERS $WEAVIATE_BATCH_NUM_WORKERS

# Zilliz - VectorDB
ENV ZILLIZ_COLLECTION $ZILLIZ_COLLECTION
ENV ZILLIZ_URI $ZILLIZ_URI
ENV ZILLIZ_USER $ZILLIZ_USER
ENV ZILLIZ_PASSWORD $ZILLIZ_PASSWORD

# Milvus - VectorDB
ENV MILVUS_COLLECTION $MILVUS_COLLECTION
ENV MILVUS_HOST $MILVUS_HOST
ENV MILVUS_PORT $MILVUS_PORT
ENV MILVUS_USER $MILVUS_USER
ENV MILVUS_PASSWORD $MILVUS_PASSWORD

# Qdrant - VectorDB
ENV QDRANT_URL $QDRANT_URL
ENV QDRANT_PORT $QDRANT_PORT
ENV QDRANT_GRPC_PORT $QDRANT_GRPC_PORT
ENV QDRANT_API_KEY $QDRANT_API_KEY
ENV QDRANT_COLLECTION $QDRANT_COLLECTION

# Redis - VectorDB
ENV REDIS_HOST $REDIS_HOST
ENV REDIS_PORT $REDIS_PORT
ENV REDIS_PASSWORD $REDIS_PASSWORD
ENV REDIS_INDEX_NAME $REDIS_INDEX_NAME
ENV REDIS_DOC_PREFIX $REDIS_DOC_PREFIX
ENV REDIS_DISTANCE_METRIC $REDIS_DISTANCE_METRIC
ENV REDIS_INDEX_TYPE $REDIS_INDEX_TYPE


# Expose the port
EXPOSE 8000
